# Basic of Tensorflow

### Topic

- import tensorflow
- version check
- 0 to 4 Rank Tensor
- Rank Verification
- Numpy conversion
- Instanct Array Generation:
- eye matrix
- fill
- linspace
- Ones, Zeros
- Random.normal
- Indexcing & Slicing, Controlling randomness
- Filtering
- Linear Algebra (det, cross product, eig, global norm, svd)
- Statistics:
- Reduce Mean (column/row wise mean)
- argmax, argmin, cov

In [1]:
import tensorflow as tf

In [ ]:
tf.__version__


'2.10.0'

# 0 - Rank Tensor

In [ ]:
scaler = tf.Variable(3, dtype=tf.float32, name='scalar')
scaler

# tf.Variable, 0 rank, dimension shape, numpy version

<tf.Variable 'scalar:0' shape=() dtype=float32, numpy=3.0>

#### Extracting Numpy Values


In [ ]:
scaler.numpy()    # directly accessing numpy value tensor/ convert tensor into numpy

3.0

#### Getting / Verify the rank of tensor

In [ ]:
# output numpy 0, representing 0 rank tensor, 0 mean 0 dimension
tf.rank(scaler)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

# Rank 1 - Tensor

#### About Rank-1 Tensor

- This is kind of vector/ arrays
- For scaler we have 0 Dimension
- for array/vector (Rank 1 Tensor), having 1D

In [ ]:
vector = tf.Variable([1,2,3,], dtype=tf.int32, name='vector')
vector
# output shape (3,) 3,0 e.g 3 rows/values, this is 1D, 

<tf.Variable 'vector:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [ ]:
# Converting vector into numpy , extracted as numpy array
vector.numpy()

array([1, 2, 3])

In [ ]:
# Rank of this matrix (Rank 1 - Tensor), numpy=1 e.g Rank 1 - Tensor or thats mean 1D is there
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Rank 2 - Tensor

In [ ]:
matrix = tf.constant([
    [4,2],
    [5,3]
], dtype=tf.int32, name='matrix')
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [5, 3]])>

In [ ]:
# Rank Verification
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Rank 3 - Tensor

- [1,2,3] & [2,6,7] represent the 3 color channel as RGB
- Return 3D array as numpy one
- Shape (2,2,3) 2 rows, 2 cols and 3 values(RGB) in each cell

In [7]:
image = tf.constant([
    [[1,2,3], [2,6,7]],
    [[1,2,3], [2,6,7]]
], dtype=tf.int32, name='imange')
image

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 6, 7]],

       [[1, 2, 3],
        [2, 6, 7]]])>

In [9]:
# Extract numpy
image.numpy()

array([[[1, 2, 3],
        [2, 6, 7]],

       [[1, 2, 3],
        [2, 6, 7]]])

In [8]:
# Getting rank
tf.rank(image)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

# Instant Array Generation

#### Eye Matrix

- rows & columns need to provide
- by default its float32
- Identity Matrix
- Diagonal 1

In [11]:
tf.eye(2,2)  # 2,2 tha mean we need to provide number of rows & cols
# by default its float 32

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [ ]:
tf.eye(2,2) 

In [12]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

#### Mentioning dtype & name

In [14]:
tf.eye(3,3, dtype=tf.float16, name='eye')

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float16)>

In [15]:
tf.fill((3,3), 8.8)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8]], dtype=float32)>

In [16]:
tf.fill((3,3), 5.5)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]], dtype=float32)>

In [17]:
tf.linspace(0,1,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

In [18]:
tf.linspace(1,10,20)

<tf.Tensor: shape=(20,), dtype=float64, numpy=
array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])>

In [20]:
tf.ones((3,3))  # 3x3 matrix filled with one

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
tf.random.normal(((3,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5441036 ,  0.7301311 , -1.4040653 ],
       [-0.37823948,  1.529557  ,  1.1220106 ],
       [ 0.9094063 , -1.6381341 ,  0.22286439]], dtype=float32)>

In [23]:
tf.random.normal(((3,3)), mean=0, stddev=1)
# defining mean & std, according that number will be generated accordingly

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9708281 , -0.12516491,  1.6937569 ],
       [-0.2841523 ,  0.37417608, -0.5967232 ],
       [ 1.3251942 ,  0.83843184,  0.72445154]], dtype=float32)>

#### Verify mean

In [ ]:
# Test1: this will return error, because directly  we dont have fn as .mean() to access, first need to extact numpy then apply mean
tf.random.normal(((3,3)), mean=0, stddev=1).mean() 

In [26]:
# Test 2: extract numpy and apply mean, this return the mean of whole matrix
tf.random.normal(((3,3)), mean=0, stddev=1).numpy().mean()

0.024944915

# Indexing & Slicing

In [37]:
tensor = tf.random.normal(((3,3)), mean=0, stddev=1)
tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3193921 ,  0.39596778,  0.26580188],
       [-0.7246842 ,  0.51222897,  0.43289015],
       [ 2.552994  ,  1.2195656 ,  0.48654377]], dtype=float32)>

In [38]:
tensor[0] # returning 1st rows

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.3193921 , 0.39596778, 0.26580188], dtype=float32)>

In [39]:
tensor[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.7246842 ,  0.51222897,  0.43289015], dtype=float32)>

In [40]:
tensor[2] # returning 3rd row

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.552994  , 1.2195656 , 0.48654377], dtype=float32)>

In [41]:
tensor[0,0] # first rows, first value

<tf.Tensor: shape=(), dtype=float32, numpy=1.3193921>

In [42]:
tensor[0,1] # first rows, 2nd value

<tf.Tensor: shape=(), dtype=float32, numpy=0.39596778>

In [43]:
tensor[0,2] # first rows, 3rd value

<tf.Tensor: shape=(), dtype=float32, numpy=0.26580188>

In [44]:
tensor[1,0]  # 2nd row, 1st value

<tf.Tensor: shape=(), dtype=float32, numpy=-0.7246842>

In [45]:
tensor[1,1]  # 2nd row, 2nd value

<tf.Tensor: shape=(), dtype=float32, numpy=0.51222897>

In [46]:
tensor[1,2]  # 2nd row, 3rd value

<tf.Tensor: shape=(), dtype=float32, numpy=0.43289015>

In [47]:
tensor[2,0]  # 3rd row, 1st value

<tf.Tensor: shape=(), dtype=float32, numpy=2.552994>

In [48]:
tensor[2,1]  # 3rd row, 2nd value

<tf.Tensor: shape=(), dtype=float32, numpy=1.2195656>

In [49]:
tensor[2,2]  # 3rd row, 3rd value

<tf.Tensor: shape=(), dtype=float32, numpy=0.48654377>

In [50]:
tensor[0,1:] # 1st row, 2nd value to end or 1st row and last 2 columns

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.39596778, 0.26580188], dtype=float32)>

In [53]:
tensor[1,1:] # 2nd row, 2nd value to end or 2nd row & all cols, or last 2 cols

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.51222897, 0.43289015], dtype=float32)>

In [54]:
tensor[2,1:]  # 3rd row, 2nd value to end or 2nd row & all cols, or last 2 cols

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2195656 , 0.48654377], dtype=float32)>

In [52]:
tensor[0,2:] # 1st row, 3rd value

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.26580188], dtype=float32)>

In [51]:
tensor[:,1:] # 1st row, 2nd col to all cols or last two cols

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.39596778, 0.26580188],
       [0.51222897, 0.43289015],
       [1.2195656 , 0.48654377]], dtype=float32)>

In [56]:
tensor[:,2:]  # 1st rows, 3rd cols to all cols

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.26580188],
       [0.43289015],
       [0.48654377]], dtype=float32)>

In [57]:
tensor[0:,2:] # alternaive

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.26580188],
       [0.43289015],
       [0.48654377]], dtype=float32)>

In [67]:
tensor[1:,1:2] # 2nd row, 2 col to all cols

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.51222897],
       [1.2195656 ]], dtype=float32)>

In [72]:
tensor[0:,1:2] # 1 row, 2 col to last cols

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.39596778],
       [0.51222897],
       [1.2195656 ]], dtype=float32)>

In [81]:
tensor[:,1:2] # 1 row, 2 col to last cols , alternative method

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.39596778],
       [0.51222897],
       [1.2195656 ]], dtype=float32)>

In [75]:
tensor[0:,0:1] # 1 row, 1 col to last cols   [row:start col: end cols]

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 1.3193921],
       [-0.7246842],
       [ 2.552994 ]], dtype=float32)>

In [82]:
tensor[:,:1] # 1 row, 1 col to last cols   [row:start col: end cols], Alternaive

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 1.3193921],
       [-0.7246842],
       [ 2.552994 ]], dtype=float32)>

In [83]:
tensor[:,:2]   # 1st row , 1 col to 2nd col

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.3193921 ,  0.39596778],
       [-0.7246842 ,  0.51222897],
       [ 2.552994  ,  1.2195656 ]], dtype=float32)>

In [95]:
tensor[0:,0:2] # # 1st row, 1 col to all col upto 2nd cols, alternative

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.3193921 ,  0.39596778],
       [-0.7246842 ,  0.51222897],
       [ 2.552994  ,  1.2195656 ]], dtype=float32)>

In [84]:
tensor[:,:3]  # 1st row , 1 col to 3rd col

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3193921 ,  0.39596778,  0.26580188],
       [-0.7246842 ,  0.51222897,  0.43289015],
       [ 2.552994  ,  1.2195656 ,  0.48654377]], dtype=float32)>

In [88]:
tensor[:,:] # all rows & all cols, altertive

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3193921 ,  0.39596778,  0.26580188],
       [-0.7246842 ,  0.51222897,  0.43289015],
       [ 2.552994  ,  1.2195656 ,  0.48654377]], dtype=float32)>

In [86]:
tensor[1:,1:3]  # 2nd row, 2nd col to last cols

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.51222897, 0.43289015],
       [1.2195656 , 0.48654377]], dtype=float32)>

In [87]:
tensor[1:,1:]  # 2nd row, 2nd col to last all cols, Alternaive

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.51222897, 0.43289015],
       [1.2195656 , 0.48654377]], dtype=float32)>

In [90]:
tensor[1:,0:2] # 2nd row, 1st col to all cols upto 2nd cols

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7246842 ,  0.51222897],
       [ 2.552994  ,  1.2195656 ]], dtype=float32)>

In [100]:
tensor[1:,0:3] # 2nd row, 1st col to all cols upto 3nd cols

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7246842 ,  0.51222897,  0.43289015],
       [ 2.552994  ,  1.2195656 ,  0.48654377]], dtype=float32)>

#### Controlling Randomness

In [133]:
tf.random.set_seed(42)  # must be given in same cell, if provide in seperate cell it will not work
tensor2 = tf.random.normal(((3,3)), mean=0, stddev=1)
tensor2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [135]:
tensor2[:-1,1:] # 1st row, -1 mean, 3rd value -1 e.g 2nd value

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8426258,  0.3194337],
       [-2.3880599, -1.0392479]], dtype=float32)>

In [136]:
tensor2[:,1:] # 1st row, all values

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8426258,  0.3194337],
       [-2.3880599, -1.0392479],
       [ 0.539707 ,  1.6994323]], dtype=float32)>

In [137]:
tensor2[:-1,2:] 

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 0.3194337],
       [-1.0392479]], dtype=float32)>

In [139]:
tensor2[:-2,0:] # Returning Fist rows

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.3274685, -0.8426258,  0.3194337]], dtype=float32)>

In [140]:
tensor2[0] # returning 1st rows, alternative

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.3274685, -0.8426258,  0.3194337], dtype=float32)>

In [142]:
tensor2[:-2,1:] # 1st row, 2nd value to end or 1st row and last 2 columns

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.8426258,  0.3194337]], dtype=float32)>

In [143]:
tensor2[0,1:] # 1st row, 2nd value to end or 1st row and last 2 columns, Alternative

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.8426258,  0.3194337], dtype=float32)>

# Filtering

In [154]:
tf.random.set_seed(42)
tensor3 = tf.random.normal(((3,3)), mean=0, stddev=1)
tensor3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [155]:
tensor3 [tensor3 > 0.5]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.539707 , 1.6994323], dtype=float32)>

In [156]:
tensor3 [tensor3 < 0.5]

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([ 0.3274685, -0.8426258,  0.3194337, -1.4075519, -2.3880599,
       -1.0392479, -0.5573232], dtype=float32)>

# Linear Algebra

### About Linear Algebra

- Linear Algebra is available in tensorflow & numpy

#### Determenant of Tensor

In [159]:
tf.linalg.det(tensor3)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.3167505>

In [161]:
# Cross Product
tf.linalg.cross(tensor3, tensor3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Instead of using tf everytime, we can simply import linear Algebra from tensor as follows

### Import Linear Algebra from tensor

In [162]:
from tensorflow import linalg

In [164]:
tf.random.set_seed(42)
tensor4 = tf.random.normal(((3,3)), mean=0, stddev=1)
tensor4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

In [165]:
linalg.det(tensor4)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.3167505>

In [166]:
linalg.cross(tensor4, tensor4)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [167]:
linalg.inv(tensor4)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.81020594, -0.3716652 , -0.37957337],
       [-0.6883039 , -0.17016001,  0.0253196 ],
       [ 0.48429644, -0.06784681,  0.45591095]], dtype=float32)>

##### Notes on Eigenvalues

- Eigenvalues is Linear Algebra concept
- Eigenvalues: for each linear independent rows, we can have some eigenvalues, just kind of squeezing
- We can represent one vector in another vector space, for that eigenvalues plays an important roles
- eigenvalue is very useful for 'gradient calculation' & PCA
- in output first array is Eigenvalues values, & 2nd array is eigen vector
- for every eigen vector its has repective eigen values
- its in kind of complex data type

In [168]:
linalg.eig(tensor4)

(<tf.Tensor: shape=(3,), dtype=complex64, numpy=
 array([ 1.170743 +0.4760183j,  1.170743 -0.4760183j,
        -2.7026455+0.j       ], dtype=complex64)>,
 <tf.Tensor: shape=(3, 3), dtype=complex64, numpy=
 array([[ 0.55169594-0.09588708j,  0.55169594+0.09588708j,
          0.27507606+0.j        ],
        [-0.3903153 -0.04294623j, -0.3903153 +0.04294623j,
          0.95786667+0.j        ],
        [ 0.56971145+0.4557145j ,  0.56971145-0.4557145j ,
         -0.0826112 +0.j        ]], dtype=complex64)>)

In [169]:
# Global Norm
linalg.global_norm([tensor4, tensor4*2])

<tf.Tensor: shape=(), dtype=float32, numpy=8.115825>

In [170]:
linalg.solve(tensor4*2, tensor4*3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.5000000e+00,  8.5252303e-08,  8.4692644e-08],
       [ 0.0000000e+00,  1.5000000e+00, -1.6052263e-07],
       [ 0.0000000e+00, -1.1546527e-07,  1.5000001e+00]], dtype=float32)>

In [172]:
# Singular Value Decomposition, this is also available in numpy
linalg.svd(tensor4)  

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.1246624 , 1.6443776 , 0.84014195], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.13203673,  0.16672823,  0.9771224 ],
        [-0.93144065,  0.31634682, -0.17984265],
        [ 0.33909434,  0.9338773 , -0.11352797]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.34526232, -0.55409896,  0.7574749 ],
        [ 0.80604094, -0.23834218, -0.5417482 ],
        [ 0.48072037,  0.797601  ,  0.36433583]], dtype=float32)>)

In [174]:
import numpy as np

In [175]:
np.linalg.svd(tensor4)

(array([[ 0.13203672, -0.16672814, -0.9771223 ],
        [ 0.9314405 , -0.31634676,  0.17984262],
        [-0.3390943 , -0.9338771 ,  0.11352795]], dtype=float32),
 array([3.1246614 , 1.6443771 , 0.84014183], dtype=float32),
 array([[-0.34526232, -0.8060409 , -0.48072037],
        [ 0.55409896,  0.2383422 , -0.797601  ],
        [-0.7574749 ,  0.5417482 , -0.36433583]], dtype=float32))

# Statistics

In [179]:
tf.random.set_seed(42)
tensor5 = tf.random.normal(((3,3)), mean=0, stddev=1)
tensor5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

##### About Reduce Mean

- recursive in nature

In [181]:
tf.reduce_mean(tensor5)  # mean of whole tensor, can be fetche axis wise mean also

<tf.Tensor: shape=(), dtype=float32, numpy=-0.3720852>

##### Axis wise Mean 

In [182]:
# Column wise mean
tf.reduce_mean(tensor5, axis=1)  

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.0652412 , -1.61162   ,  0.56060535], dtype=float32)>

In [183]:
# Row wise mean
tf.reduce_mean(tensor5, axis=0)  

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.5458022 , -0.8969929 ,  0.32653937], dtype=float32)>

#### Reduce Sum

In [184]:
tf.reduce_sum(tensor5) 

<tf.Tensor: shape=(), dtype=float32, numpy=-3.3487668>

In [185]:
# Column wise reduce sum
tf.reduce_sum(tensor5, axis=1) 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.1957236, -4.83486  ,  1.6818161], dtype=float32)>

In [186]:
# Row wise reduce sum
tf.reduce_sum(tensor5, axis=0) 

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.6374066, -2.6909788,  0.9796181], dtype=float32)>

In [187]:
tf.argmax(tensor5)   # armax,armin is very useful for neural network

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 2], dtype=int64)>

In [188]:
# Column wise argmax
tf.argmax(tensor5, axis=1)  # output 0: 1st col, 1 st postion we have the highest value, 2: for 2nd col, its in 2nd position; 2:for 3rd col we have in 2nd poistion  

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 2], dtype=int64)>

In [189]:
tf.argmax(tensor5, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 2], dtype=int64)>

In [190]:
tf.argmin(tensor5, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 0], dtype=int64)>

In [191]:
tf.argmin(tensor5, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1], dtype=int64)>

- Here, Coverince not available in tensoflow, for that we need to use numpy, as its very compatiable with numpy
- that mean combining tensorflow & numply we can perform all kinds of operaions

In [192]:
# Coverience
np.cov(tensor5)

array([[0.45326125, 0.45195455, 0.00765138],
       [0.45195455, 0.48605625, 0.21996276],
       [0.00765138, 0.21996276, 1.27356387]])